# Generated by Django 4.0.4 on 2023-07-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='type_social_network',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('YouTube', 'YouTube'), ('whatsApp', 'whatsApp')], max_length=30, verbose_name='Enlace'),
        ),
    ]
