# Generated by Django 4.0.4 on 2023-07-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_socialnetwork_type_social_network'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='recommended',
            options={'verbose_name': 'PaginaRecomendada', 'verbose_name_plural': 'PaginasRecomendadas'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Sitio', 'verbose_name_plural': 'Sitios'},
        ),
        migrations.AlterModelOptions(
            name='siteimages',
            options={'verbose_name': 'ImagenSitio', 'verbose_name_plural': 'ImagenesSitios'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'RedSocalSitio', 'verbose_name_plural': 'RedesSocialesSitios'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='fake_name',
        ),
        migrations.AlterField(
            model_name='siteimages',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_images', to='core.site', verbose_name='Sitio'),
        ),
    ]
