# Generated by Django 4.0.4 on 2023-07-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fake_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nickname'),
        ),
    ]
