# Generated by Django 4.0.4 on 2023-07-26 19:06

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.TextField(verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='site',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='site',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='site',
            name='quality',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación'),
        ),
    ]
