# Generated by Django 4.0.4 on 2023-07-26 21:44

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_image_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommended',
            options={'verbose_name': 'Pagina Recomendada', 'verbose_name_plural': 'Paginas Recomendadas'},
        ),
        migrations.AlterModelOptions(
            name='siteimages',
            options={'verbose_name': 'Imagen Sitio', 'verbose_name_plural': 'Imagenes Sitios'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Red Socal Sitio', 'verbose_name_plural': 'Redes Sociales Sitios'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.TextField(verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='quality',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site', verbose_name='Sitio'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='recommended',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='siteimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='type_social_network',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('YouTube', 'YouTube'), ('whatsApp', 'whatsApp')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=100, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono'),
        ),
    ]
