# Generated by Django 4.0.4 on 2023-07-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_recommended_options_alter_siteimages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.TextField(verbose_name='Comentario'),
        ),
    ]
