# Generated by Django 4.0.4 on 2023-07-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_site_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteimages',
            options={'verbose_name': 'Imagen Del Sitio', 'verbose_name_plural': 'Imagenes De Los Sitios'},
        ),
    ]
