# Generated by Django 4.0.4 on 2023-07-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_siteimages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteimages',
            options={},
        ),
    ]
