# Generated by Django 4.0.4 on 2023-08-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_siteimages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Precio'),
        ),
    ]
